### PR TITLE
Add benchmarks

### PR DESCRIPTION
**Pull request by durch**
Benchmark reports are in the [`README`](https://github.com/nymtech/coconut/tree/benchmark/coconut-rs#benchmarks). 

### Edit

Aggregate benchmarks to `produce_blinded_signatures` and `unblind_prove_and_verify`. I've also built out scaffolding to test both with varying number of authorities. So far it seems that both scale quite a bit worse then linear. Not sure if `threshold` plays a part we can vary it as well.

I've also cleaned up the `README` so that we only link to the global reports `index.html`

### CODE REVIEW

**Comment by jstuczyn** [comment]
I'm not sure how to feel about the bloat added by putting `target` here - I like the fact you're able to view the reports but it feels weird.

Also, we should definitely benchmark things with varying parameters. Because for example, it might be relatively quick and cheap to produce signature from, say for argument sake, 3 signing authorities (and aggregate their keys) while it could be expensive for say 100 of them - it would be interesting to see how it changes.
I guess the same would apply for number of attributes - the proofs are definitely bulkier, both size-wise and computation time-wise as more private attributes are added. I don't remember how it changes with public attributes.

**Comment by durch** [comment]
> I'm not sure how to feel about the bloat added by putting target here - I like the fact you're able to view the reports but it feels weird.

**Comment by jstuczyn** [comment]
Looks good, I would just maybe add two additional benchmark functions - how does credential issuance / verification varies with different number of attributes, say 1, 3 and 10.

**Comment by durch** [comment]
Cleaned up benchmarks a bit, so less cruft in repo, its looking good

**Review by jstuczyn — APPROVED** [review]

**Pull request merged**
